### PR TITLE
Remove goo.gl link shortener

### PR DESCRIPTION
**Pull request by sburris0**
Might as well just link to the actual page, the link shortener isn't helpful

### CODE REVIEW

**Comment by coding-horror** [comment]
The whole point of this was to keep the link very short so it could be manually typed in relatively easily, so I'm unclear why we want to make this change?

**Comment by sburris0** [comment]
I was just looking to avoid using a Google service, I've switched it to is.gd instead

**Comment by coding-horror** [comment]
OK, since we're not really worried about losing the link (e.g. the link shortening service going under, no longer redirecting shortened links) I think that is fine.. thanks!!

**Comment by waldyrious** [comment]
Note that Wikimedia now has its own URL shortener, at https://w.wiki. The page linked here can be shortened as `https://w.wiki/qYn`. Would a PR changing the URL be welcome?

**Comment by coding-horror** [comment]
Sure that sounds good thanks!!

**Pull request merged**
