### PR TITLE
minor tweaks to the help page

### PR DESCRIPTION
**Pull request by waldyrious**
- "A paragraph" --> "Another paragraph", to better evidence its relationship to the first paragraph.
- Add colon after "horizontal rule", to call out the attention to the rule itself. Also, decapitalize "Rule".

### CODE REVIEW

**Comment by coding-horror** [comment]
The word "another" is too big on mobile, otherwise this is OK. But I need the "another" removed.

**Comment by waldyrious** [comment]
@coding-horror I'm not sure what you mean by "too big" -- could you clarify?

Here's what the current site looks like on my phone:

**Comment by coding-horror** [comment]
Try it on the emulator in iPhone 5 (smallest modern phone, iPhone SE is
also this size) it creates three lines where it used to be two.

The extra word there is not necessary.

**Comment by waldyrious** [comment]
> it creates three lines where it used to be two.

I don't see why that's so problematic.

> The extra word there is not necessary.

I disagree, as explained in the first sentence of this PR, but it's not a big deal -- I'll remove it.

**Comment by waldyrious** [comment]
@coding-horror any comments on the closure? I did the changes you requested.

**Comment by coding-horror** [comment]
sorry, I just figured I neglected it for 4 years so I closed it out of shame 😊

**Comment by waldyrious** [comment]
No worries, I'm pretty sure I have other open PRs older than that! 😄

If you're open to accept the PR, I'm still willing to make any necessary changes (rebase, squash, etc.) to get it into a mergeable state.

**Comment by coding-horror** [comment]
Sure, if you're willing let's try again! I apologize for my tardiness

**Comment by waldyrious** [comment]
No worries! I should have made it clearer back then that the changes had been made and this was ready. Please reopen the PR whenever's convenient.

**Comment by coding-horror** [comment]
I can't reopen since it says "repository that has submitted this PR has been deleted"

**Comment by waldyrious** [comment]
Oh, I see! That's weird, I don't usually delete forks that have open PRs... I guess this was an overlook. Sorry for the confusion and unnecessary back-and-forth. I'll submit a new PR.

**Pull request closed without merging**
